#!/usr/bin/env python3
"""
PES comparison figure using ``predict``-mode output files.

This script reads the ``_labels.txt`` files generated by
``python -m augernet --config configs/predict_pes_EQ.yml`` (and the IN variant)
and pairs the GNN predictions with the DFT reference data in ``pes/all_files/``.

**Prerequisites** — run these two commands first::

    cd cebe_pred
    python -m augernet --config configs/predict_pes_EQ.yml
    python -m augernet --config configs/predict_pes_IN.yml

Output (all in ``pngs/``):

    ``pes_predict_comparison.{png,pdf}``      — 2-panel  (methanol + methane)
    ``pes_predict_4panel.{png,pdf}``          — 4-panel  (all molecules)

Usage::

    cd cebe_pred && python publication_plots_pes_predict.py
"""

import os
import re
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
PNG_DIR      = os.path.join(SCRIPT_DIR, 'pngs')
PES_DIR      = os.path.join(SCRIPT_DIR, 'pes_results')
PES_REF_DIR  = os.path.join(SCRIPT_DIR, 'pes', 'all_files')
PREDICT_DIR  = os.path.join(SCRIPT_DIR, 'predict_results', 'outputs')
os.makedirs(PNG_DIR, exist_ok=True)
os.makedirs(PES_DIR, exist_ok=True)

# ── Model labels → predict-mode output filenames ────────────────────────────
#    Each labels file is {model_id}_fold{fold}_labels.txt
MODEL_CONFIGS = [
    {
        'label':      'EGNN',
        'labels_file': 'cebe_035_butina_EQ3_h64_fold5_labels.txt',

    },
    {
        'label':      'IGNN',
        'labels_file': 'cebe_035_butina_IN3_h64_fold5_labels.txt',
    },
]

# ── Molecule metadata (2-panel figure: methanol + methane) ───────────────────
MOLECULES = {
    'methanol': {
        'coord_label': r'C–O ($\AA$)',
        'eq_bond':     1.4193,
        'exp_cebe':    292.3,
        'xlim':        (1.09, 1.89),
        'ylim':        (291.6, 292.6),
        'multiref':    os.path.join(PES_REF_DIR, 'methanol_multiref_pes.txt'),
    },
    'methane': {
        'coord_label': r'C–H ($\AA$)',
        'eq_bond':     1.087,
        'exp_cebe':    290.8,
        'xlim':        (1.0, 1.46),
        'ylim':        (290, 291.2),
        'multiref':    os.path.join(PES_REF_DIR, 'methane_multiref_pes.txt'),
    },
}

# ── All 4 molecules for the 4-panel figure ──────────────────────────────────
MOLECULES_ALL = {
    'methanol': {
        'title':       'Methanol',
        'coord_label': r'C–O ($\AA$)',
        'eq_bond':     1.4193,
        'exp_cebe':    292.3,
        'multiref':    os.path.join(PES_REF_DIR, 'methanol_multiref_pes.txt'),
    },
    'methane': {
        'title':       'Methane',
        'coord_label': r'C–H ($\AA$)',
        'eq_bond':     1.087,
        'exp_cebe':    290.8,
        'multiref':    os.path.join(PES_REF_DIR, 'methane_multiref_pes.txt'),
    },
    'fluoromethane': {
        'title':       'Fluoromethane',
        'coord_label': r'C–F ($\AA$)',
        'eq_bond':     1.383,
        'exp_cebe':    293.6,
    },
    'ethene': {
        'title':       'Ethene',
        'coord_label': r'H–C–C–H dihedral (°)',
        'eq_bond':     None,         # equilibrium is planar (0° / 180°)
    },
}

# Plot colours / markers
MODEL_COLORS  = ['tab:orange', 'tab:green', 'tab:purple', 'tab:brown']
MODEL_MARKERS = ['s', 'D', '^', 'v']


# ═══════════════════════════════════════════════════════════════════════════════
#  Parse a predict-mode _labels.txt file
# ═══════════════════════════════════════════════════════════════════════════════

def parse_labels_file(path):
    """Parse a predict-mode ``_labels.txt`` and return mol_name → mean carbon CEBE.

    Returns
    -------
    dict : {str: float}
        Mapping of molecule name (e.g. ``'methane_00'``) to the mean
        predicted CEBE across all carbon atoms in that structure.
    """
    results = {}
    current_mol = None
    carbon_preds = []

    with open(path) as f:
        for line in f:
            line = line.rstrip('\n')

            # Molecule header: # --- methane_00 ---
            m = re.match(r'^# --- (.+?) ---', line)
            if m:
                # Save previous molecule
                if current_mol is not None:
                    results[current_mol] = (
                        np.mean(carbon_preds) if carbon_preds else np.nan
                    )
                current_mol = m.group(1)
                carbon_preds = []
                continue

            # Skip other comment / blank lines
            if line.startswith('#') or line.strip() == '':
                continue

            # Data line:  "  C      290.3692" or "  H*      -3.4282"
            parts = line.split()
            if len(parts) >= 2:
                sym = parts[0]
                val = float(parts[1])
                # Carbon atom (no * marker)
                if sym == 'C':
                    carbon_preds.append(val)

    # Save last molecule
    if current_mol is not None:
        results[current_mol] = (
            np.mean(carbon_preds) if carbon_preds else np.nan
        )

    return results


# ═══════════════════════════════════════════════════════════════════════════════
#  Load predictions (shared helper)
# ═══════════════════════════════════════════════════════════════════════════════

def _load_model_predictions():
    """Return dict  model_label → {mol_name: mean_carbon_cebe}."""
    model_preds = {}
    for mcfg in MODEL_CONFIGS:
        path = os.path.join(PREDICT_DIR, mcfg['labels_file'])
        if not os.path.exists(path):
            print(f"    Labels file not found: {path}")
            print(f"    Run:  python -m augernet --config configs/predict_pes_EQ.yml")
            return None
        preds = parse_labels_file(path)
        model_preds[mcfg['label']] = preds
        print(f"  Loaded {len(preds)} predictions from {mcfg['labels_file']}")
    return model_preds


# ═══════════════════════════════════════════════════════════════════════════════
#  Plot a single PES panel
# ═══════════════════════════════════════════════════════════════════════════════

def _plot_pes_panel(ax, mol_name, mol_info, model_preds, *,
                    panel_label=None, show_ylabel=True, show_legend=True):
    """Draw one PES comparison panel on *ax*.

    Parameters
    ----------
    ax : matplotlib Axes
    mol_name : str  – key into the PES reference files (e.g. 'methane')
    mol_info : dict – metadata (coord_label, eq_bond, multiref, …)
    model_preds : dict – model_label → {mol_name_XX: cebe}
    panel_label : str or None – e.g. '(a)' drawn in the top-left corner
    show_ylabel : bool
    show_legend : bool
    """
    coord_label = mol_info['coord_label']

    # Load DFT reference PES (coordinate + single-ref CEBE)
    pes_file = os.path.join(PES_REF_DIR, f'{mol_name}_pes.txt')
    if not os.path.exists(pes_file):
        print(f'  ⚠  PES file not found: {pes_file}')
        return
    pes_arr   = np.loadtxt(pes_file)
    coords    = pes_arr[:, 0]
    calc_cebe = pes_arr[:, 1]
    n_struct  = len(coords)

    # Plot DFT single-reference
    ax.plot(coords, calc_cebe, 'o-', color='tab:blue', linewidth=2,
            markersize=5, label='MC-PDFT', zorder=10)

    # Plot multi-reference if available
#     multiref_path = mol_info.get('multiref')
#     if multiref_path and os.path.exists(multiref_path):
#         mr = np.loadtxt(multiref_path)
#         ax.plot(mr[:, 0], mr[:, 1], '^-', color='tab:purple',
#                 linewidth=2, markersize=5, label='Multi-ref.', zorder=9)

    # Plot each model's GNN predictions & write CSVs
    for m_idx, mcfg in enumerate(MODEL_CONFIGS):
        label = mcfg['label']
        preds = model_preds[label]

        gnn_cebe = np.array([
            preds.get(f'{mol_name}_{i:02d}', np.nan)
            for i in range(n_struct)
        ])

        color  = MODEL_COLORS[m_idx % len(MODEL_COLORS)]
        marker = MODEL_MARKERS[m_idx % len(MODEL_MARKERS)]
        ax.plot(coords, gnn_cebe, f'{marker}--', color=color,
                linewidth=2, markersize=5, label=label)

        # Stats
        valid = ~np.isnan(gnn_cebe)
        if valid.sum() > 0:
            mae = np.mean(np.abs(gnn_cebe[valid] - calc_cebe[valid]))
            print(f'  {mol_name:<18s}  {label:<10s}  '
                  f'MAE = {mae:.4f} eV  ({valid.sum()} pts)')

        # Write CSV
        csv_stem = mcfg['labels_file'].replace('_labels.txt', '')
        csv_path = os.path.join(
            PES_DIR, f'pes_{mol_name}_{csv_stem}.csv',
        )
        np.savetxt(
            csv_path,
            np.column_stack([coords, calc_cebe, gnn_cebe]),
            delimiter=',',
            header='coordinate,calc_cebe,gnn_cebe',
            comments='',
            fmt='%.10f',
        )

    # Equilibrium reference line
    eq_bond = mol_info.get('eq_bond')
    if eq_bond is not None:
        ax.axvline(eq_bond, color='black', ls=':', lw=1.5, alpha=0.7)

    ax.set_xlabel(coord_label, fontsize=14, fontweight='bold')
    if show_ylabel:
        ax.set_ylabel('CEBE (eV)', fontsize=14, fontweight='bold')
    title = mol_info.get('title', mol_name.capitalize())
    #ax.set_title(title, fontsize=16, fontweight='bold')
    if show_legend:
        ax.legend(fontsize=11, framealpha=0.85, fancybox='round')
    ax.grid(True, alpha=0.2)
    ax.tick_params(axis='both', labelsize=12)

    xlim = mol_info.get('xlim')
    if xlim is not None:
        ax.set_xlim(xlim)
    ylim = mol_info.get('ylim')
    if ylim is not None:
        ax.set_ylim(ylim)

    if panel_label is not None:
        ax.text(0.03, 0.95, panel_label, transform=ax.transAxes,
                fontsize=16, fontweight='bold', va='top')


# ═══════════════════════════════════════════════════════════════════════════════
#  2-panel figure (methanol + methane) — original
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    print('=' * 72)
    print('  PES Predict-Mode Comparison')
    print('=' * 72)

    # ── Load predictions from each model's labels file ────────────────────
    model_preds = _load_model_predictions()
    if model_preds is None:
        return

    # ── Plot ──────────────────────────────────────────────────────────────
    sns.set_style('whitegrid')
    n_mols = len(MOLECULES)
    fig, axes = plt.subplots(1, n_mols, figsize=(6 * n_mols, 5))
    if n_mols == 1:
        axes = [axes]

    for ax_idx, (ax, (mol_name, mol_info)) in enumerate(
        zip(axes, MOLECULES.items())
    ):
        _plot_pes_panel(
            ax, mol_name, mol_info, model_preds,
            show_ylabel=(ax_idx == 0),
            show_legend=(ax_idx == 0),
        )

    plt.tight_layout()
    png_path = os.path.join(PNG_DIR, 'pes_predict_comparison.png')
    pdf_path = os.path.join(PNG_DIR, 'pes_predict_comparison.pdf')
    fig.savefig(png_path, dpi=300, bbox_inches='tight')
    fig.savefig(pdf_path, bbox_inches='tight')
    print(f'\n  ✓ PES 2-panel → {png_path}')
    print(f'  ✓ PES 2-panel → {pdf_path}')
    plt.close(fig)

    print('\n  ✅  Done (2-panel).')


# ═══════════════════════════════════════════════════════════════════════════════
#  4-panel figure (all molecules)
# ═══════════════════════════════════════════════════════════════════════════════

def main_4panel():
    """Create a 2×2 figure with all four PES molecules."""
    print('=' * 72)
    print('  PES Predict-Mode — 4-Panel Comparison')
    print('=' * 72)

    model_preds = _load_model_predictions()
    if model_preds is None:
        return

    sns.set_style('whitegrid')
    panel_labels = ['(a)', '(b)', '(c)', '(d)']
    mol_items = list(MOLECULES_ALL.items())

    fig, axes = plt.subplots(2, 2, figsize=(13, 10))
    axes_flat = axes.flatten()

    for idx, (ax, (mol_name, mol_info)) in enumerate(
        zip(axes_flat, mol_items)
    ):
        _plot_pes_panel(
            ax, mol_name, mol_info, model_preds,
            panel_label=panel_labels[idx],
            show_ylabel=(idx % 2 == 0),
            show_legend=(idx == 0),
        )

    plt.tight_layout()
    png_path = os.path.join(PNG_DIR, 'pes_predict_4panel.png')
    pdf_path = os.path.join(PNG_DIR, 'pes_predict_4panel.pdf')
    fig.savefig(png_path, dpi=300, bbox_inches='tight')
    fig.savefig(pdf_path, bbox_inches='tight')
    print(f'\n  ✓ PES 4-panel → {png_path}')
    print(f'  ✓ PES 4-panel → {pdf_path}')
    plt.close(fig)

    print('\n  ✅  Done (4-panel).')


# ═══════════════════════════════════════════════════════════════════════════════
#  Single-panel methanol figure
# ═══════════════════════════════════════════════════════════════════════════════

def main_methanol():
    """Single-panel methanol PES with xlim ≤ 2.0 Å and ylim ≥ 291 eV."""
    print('=' * 72)
    print('  PES Predict-Mode — Methanol (single panel)')
    print('=' * 72)

    model_preds = _load_model_predictions()
    if model_preds is None:
        return

    mol_info = {
        'title':       'Methanol',
        'coord_label': r'C–O ($\AA$)',
        'eq_bond':     1.4193,
        'exp_cebe':    292.3,
        'xlim':        (1.09, 2.00),
        'ylim':        (291.0, None),
        'multiref':    os.path.join(PES_REF_DIR, 'methanol_multiref_pes.txt'),
    }

    sns.set_style('whitegrid')
    fig, ax = plt.subplots(figsize=(7, 5))

    _plot_pes_panel(ax, 'methanol', mol_info, model_preds,
                    show_ylabel=True, show_legend=True)

    plt.tight_layout()
    png_path = os.path.join(PNG_DIR, 'pes_predict_methanol.png')
    pdf_path = os.path.join(PNG_DIR, 'pes_predict_methanol.pdf')
    fig.savefig(png_path, dpi=300, bbox_inches='tight')
    fig.savefig(pdf_path, bbox_inches='tight')
    print(f'\n  ✓ Methanol → {png_path}')
    print(f'  ✓ Methanol → {pdf_path}')
    plt.close(fig)

    print('\n  ✅  Done (methanol).')


if __name__ == '__main__':
    main()
    main_4panel()
    main_methanol()
